### ISSUE TITLE
Show history popup with a shortcut

### ISSUE THREAD

**Issue by bitsandnumbers** [blackjackshellac/eclipse#14]
Could it be possible to show a pop-up with history triggered with a short-cut  ?

This could be implemented in different ways, but the best case scenario would be having the pop-up appear next to the mouse.

The other extension "Clipboard Indicator" allows this, but the standard menu opens, so one still have to move the mouse all the way to the top right of the screen. It's a bit cumbersome with multiple monitor set-ups.

**Comment by blackjackshellac** [comment]
You mean a keyboard shortcut to open the history menu (in the newest version here?)  I could probably do that pretty easily but I'm not sure about popping it up by the mouse.  You could easily use the keyboard to select the history you're interested in though.

Note that the history currently has to be enabled in Preferences.

**Comment by bitsandnumbers** [comment]
Yes, that's exactly what I mean. Your solution would be good too, but of course a pop-up would be preferred. I remember that such kind of pop-up existed before with an old extension for gpaste (long time ago). Don't know how Gnome-Shell would allow such behaviour today...

**Comment by blackjackshellac** [comment]
Try the version I just committed.

Ctrl+Super+M - menu
Ctrl+Super+H - history menu

**Comment by blackjackshellac** [comment]
After a lock screen I see this,

```
Apr 21 16:38:54 woot.home gnome-shell[191533]: INFO: [cl_ippie] Attaching indicator, size=100 items
Apr 21 16:38:54 woot.home gnome-shell[191533]: DEBUG: [cl_indicator] Initializing extension
Apr 21 16:38:54 woot.home gnome-shell[191533]: DEBUG: [cl_kbshortcuts] Trying to listen for hot key [accelerator=<ctrl><super>M]
Apr 21 16:38:54 woot.home gnome-shell[191533]: ERROR: [cl_kbshortcuts] Unable to grab accelerator [<ctrl><super>M]
Apr 21 16:38:54 woot.home gnome-shell[191533]: DEBUG: [cl_kbshortcuts] Trying to listen for hot key [accelerator=<ctrl><super>H]
Apr 21 16:38:54 woot.home gnome-shell[191533]: ERROR: [cl_kbshortcuts] Unable to grab accelerator [<ctrl><super>H]
```
