### ISSUE TITLE
gnome-shell 3.30

### ISSUE THREAD

**Issue by smalltimer** [blackjackshellac/eclipse#18]
Hi, thank you for writing this! Is there any chance it will be made available on gnome-shell 3.30 ? 

Cheers

**Comment by blackjackshellac** [comment]
Way too many changes between 3.34 and 3.36, let alone 3.30 and 40. It's enough supporting 3.3[68] and 40.

Sorry

**Comment by smalltimer** [comment]
Fair enough. Thanks for replying so quickly!
